ControlFocus("Open","","Edit1")
Sleep(1000)
ControlSetText("Open","","Edit1","D:\Prashant\Automation\fromGit\batch\dec2021\src\main\resources\uploadFile\image.PNG")
Sleep(10000)
ControlClick("Open","","Button1")
Sleep(5000)